apiVersion: v2
name: external-secrets
description: External Secrets operator for AdmanCorp platform
type: application
version: 1.0.0

dependencies:
  - name: external-secrets
    version: "0.14.*"
    repository: https://charts.external-secrets.io
