apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: envoy-proxy
  labels:
    release: platform
spec:
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
      path: /stats/prometheus
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/name: envoy
      app.kubernetes.io/managed-by: envoy-gateway
