apiVersion: v2
name: kube-prometheus-stack
description: kube-prometheus-stack observability for AdmanCorp platform
type: application
version: 1.0.0

dependencies:
  - name: kube-prometheus-stack
    version: "69.8.*"
    repository: https://prometheus-community.github.io/helm-charts
