apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../shared
  - ../../../platform/operators/cert-manager/overlays/prod
  - ../../../platform/operators/external-secrets/overlays/prod
  - ../../../platform/networking/gateway-api/overlays/prod
  - ../../../platform/networking/envoy-gateway/overlays/prod
  - ../../../platform/observability/kube-prometheus-stack/overlays/prod
  - ../../../platform/observability/loki/overlays/prod
  - ../../../platform/security/kyverno/overlays/prod
