apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../shared
  - ../../../platform/operators/cert-manager/overlays/uat
  - ../../../platform/operators/external-secrets/overlays/uat
  - ../../../platform/networking/gateway-api/overlays/uat
  - ../../../platform/networking/envoy-gateway/overlays/uat
  - ../../../platform/observability/kube-prometheus-stack/overlays/uat
  - ../../../platform/observability/loki/overlays/uat
  - ../../../platform/security/kyverno/overlays/uat

patches:
  - target:
      group: gateway.envoyproxy.io
      version: v1alpha1
      kind: EnvoyProxy
      name: admancorp-envoy-proxy
      namespace: networking
    patch: |-
      - op: replace
        path: /spec/provider/kubernetes/envoyService/annotations/external-dns.alpha.kubernetes.io~1hostname
        value: gcp-gw.uat.admancorp.com
