apiVersion: v2
name: admancorp-platform
description: Umbrella chart composing all AdmanCorp platform components
type: application
version: 1.0.0

dependencies:
  - name: namespaces
    version: "1.0.0"
    repository: file://../namespaces
  - name: external-secrets
    version: "1.0.0"
    repository: file://../external-secrets
  - name: envoy-gateway
    version: "1.0.0"
    repository: file://../envoy-gateway
  - name: kyverno
    version: "1.0.0"
    repository: file://../kyverno
  - name: kube-prometheus-stack
    version: "1.0.0"
    repository: file://../kube-prometheus-stack
    condition: kube-prometheus-stack.enabled
  - name: loki
    version: "1.0.0"
    repository: file://../loki
    condition: loki.enabled
  - name: alloy
    version: "1.0.0"
    repository: file://../alloy
    condition: alloy.enabled
