environment: prod
cloud: gcp
clusterSecretStore:
  enabled: true
  provider: gcp
  gcp:
    clusterLocation: ""   # zone ex: us-central1-a
    clusterName: "mc-gke" # var.cluster_name (default)

envoy-gateway:
  domain: admancorp.com
  envoyServiceHostname: gcp-gw.admancorp.com

kube-prometheus-stack:
  enabled: true

loki:
  enabled: true

alloy:
  enabled: true
