environment: uat
cloud: azure
clusterSecretStore:
  enabled: true
  provider: azure
  azure:
    vaultUrl: "https://odoo-kv.vault.azure.net"

envoy-gateway:
  domain: uat.admancorp.com
  envoyServiceHostname: az-gw.uat.admancorp.com

kube-prometheus-stack:
  enabled: true

loki:
  enabled: true

alloy:
  enabled: true
