apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../shared
  - ../../../platform/operators/cert-manager/overlays/dev
  - ../../../platform/operators/external-secrets/overlays/dev
  - ../../../platform/networking/gateway-api/overlays/dev
  - ../../../platform/networking/envoy-gateway/overlays/dev
  - ../../../platform/security/kyverno/overlays/dev
